#
# Makefile for Linux arch/m68k/amiga source directory
#

obj-y		:= config.o amiints.o cia.o chipram.o amisound.o platform.o

obj-$(CONFIG_AMIGA_DMAC)	+= dmac.o
obj-$(CONFIG_AMIGA_PCMCIA)	+= pcmcia.o
obj-$(CONFIG_AMIGA_CDTV)	+= cdtv.o
